esphome:
  name: simple

esp32:  
  board: esp32-s2-saola-1
  framework:
    type: arduino

external_components:
  - source: ../components

# Enable logging
logger:

i2c:
  scl: 1
  sda: 2

sensor:
  - platform: max30105
    infrared:
      name: IR
    red:
      name: Red
    green:
      name: Green